---
output: github_document
---
# R OpenSci ozunconference 2018 Projects

### `r emo::ji("question")``r emo::ji("memo")``r emo::ji("black_nib")`[tl - tl;dr documentation for r  functions](https://github.com/ropenscilabs/tl)

### `r emo::ji("mortar_board")``r emo::ji("page_facing_up")`[vitae - automated CV functions and templates](https://github.com/ropenscilabs/vitae)

### `r emo::ji("school")``r emo::ji("chart_with_upwards_trend")``r emo::ji("sparkles")`[learngganimate - a guide to all things gganimate](https://github.com/ropenscilabs/learngganimate)`r emo::ji("books")`

### `r emo::ji("baby")``r emo::ji("name_badge")`[ozbabynames - popular Australian baby names by sex, state and year](https://github.com/ropenscilabs/ozbabynames)

### `r emo::ji("blue_book")``r emo::ji("mag")`[simpletextr - makes Natural Language Processing simple ](https://github.com/ropenscilabs/simpletextr)

### `r emo::ji("earth_americas")``r emo::ji("repeat")``r emo::ji("earth_asia")`[geoflowr - animating geographical flows](https://github.com/ropenscilabs/geoflowr/)

### `r emo::ji("computer")``r emo::ji("mag")`[jerbs - scraping and tidying Department of employment and jobs website](https://github.com/gabyd/jerbs)

### `r emo::ji("speech_balloon")`[reviewer - better track changes and reviewing experience in R markdown](https://github.com/ropenscilabs/reviewer)`r emo::ji("memo")`

### `r emo::ji("rainbow")`[gendercoder - helpers for managing complex free-text gender entry data](https://github.com/ropenscilabs/gendercoder)`r emo::ji("busts_in_silhouette")``r emo::ji("arrow_right")``r emo::ji("woman")``r emo::ji("man")``r emo::ji("rainbow")`

### `r emo::ji("package")``r emo::ji("whale2")`[containerit - package your analysis with Docker ](https://github.com/ropenscilabs/containerit)

### `r emo::ji("walking")`[rwalkable - how walkable is a neighbourhood](https://github.com/sa-lee/rwalkable)

### `r emo::ji("bird")``r emo::ji("speech_balloon")`[UntweetdAus - tweeting underappreciated endangered species](https://github.com/ropenscilabs/UntweetdAus)`r emo::ji("ant")``r emo::ji("bug")``r emo::ji("snake")`

### `r emo::ji("book")``r emo::ji("left_right_arrow")``r emo::ji("pencil")`[syn - a synonym package](https://github.com/ropenscilabs/syn)

### `r emo::ji("clipboard")``r emo::ji("paperclip")`[bindertools - Easy initiation of R binders on github](https://github.com/ropenscilabs/bindertools)`r emo::ji("open_file_folder")`

---

If there are any projects that you know are missing please
[fork](https://github.com/ropensci/ozunconf18)
this document on GitHub, make changes, and then send a pull
request.
